### ISSUE TITLE
EOL: Ingest Michaeleen’s spreadsheet of publications, ORCIDS/authors, headshots/images and other metadata for Bering Sea Researchers

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#10]

**Comment by daniels303** [comment]
Some of this also comes from Michaeleen's spreadsheet as well.

**Comment by heesuchang** [comment]
#5 Headshots can be uploaded in the newer version of VIVO without problem. 1.8.X has a problem with the library that VIVO originally used to process thumbnails

**Comment by heesuchang** [comment]
Ingest of publications (linked to authors and journals) complete.
Ingest of metadata for investigators with also complete. (Not everyone has distinguishable ORCIDs yet but those that were available do have them on VIVO)

Only thing that remains is ingesting headshots.

On vivo.dev

**Comment by heesuchang** [comment]
Below is the .n3 file for all ingest data for production site. Can be imported to vivo.eol by "Add/Remove" on site admin page.
https://drive.google.com/open?id=0B06qDefKxUMRLW13YS0yQ0xWNm8
Below are the queries I used to compile all the triples and edited to make the above file for future reference.
https://drive.google.com/open?id=0B06qDefKxUMRY2tySXpMOVlrQjA

**Comment by heesuchang** [comment]
Imported data from dev to production. Below is an example of a publication. 
http://vivo.eol.ucar.edu/vivo/individual?uri=http%3A%2F%2Fvivo.eol.ucar.edu%2Fvivo%2Fpublication%2Fn31

**Comment by heesuchang** [comment]
Awards linked to publications in production.

**Comment by dwstott** [comment]
Head and shoulder pictures are ready to add when VIVO is updated. 
Time: 3 hours

**Comment by dwstott** [comment]
Trying VIVOPhotoDataGenerator.js that Benjamin G. contributed, but errors thrown. Will continue with this manually.

**Comment by gneissone** [comment]
I'm still subscribed to this repo :) I don't remember contributing anything by that name,
was it [the code Javed just posted](https://github.com/mjaved495/VIVOPhotoDataGenerator)? I did have some Python code to generate photos and thumbnails I could pass on but it's a little bit of a mess.

**Comment by dwstott** [comment]
Benjamin, you are correct that we were trying Javed's code. Thanks for the offer but we have to finish this up tomorrow so will either see if we can get it working, or continue as we had. 

Got this mixed up with your propertyGroupControls.js which we want to use to control the tabs better. But when we updated to v1.9.3 the tab controls stopped working. Possible problem with the html structure differing from 1.8 to 1.9 and the js getting confused?

**Comment by heesuchang** [comment]
105/144 investigators now have headshots in production.
