### ISSUE TITLE
EOL: Import more organizations from the EMDAC database and connect them to researchers and cross-reference this with Michaeleen’s spreadsheet

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#11]

**Comment by daniels303** [comment]
Don Stott has an .xls spreadsheet (BeringSea_VIVO_survey) to upload for this issue.

**Comment by dwstott** [comment]
GitHub doesn't support uploads of XLS or HTML file types.

**Comment by dwstott** [comment]
[BeringSea_VIVO_SURVEY_contacts_Jan2017.xlsx](https://github.com/NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930/files/891317/BeringSea_VIVO_SURVEY_contacts_Jan2017.xlsx)

I found how to save the older Excel spreadsheet to the newer format.

**Comment by dwstott** [comment]
decision made to limit organizational levels for investigators to lab, e.g. MML, and parent organization, e.g. NOAA .

**Comment by heesuchang** [comment]
Organizations from Michaeleen's spreadsheet have been arranged into hierarchy according to convention mentioned above, ingested and linked to investigators in VIVO

On vivo.dev

**Comment by dwstott** [comment]
Organizations arranged in production VIVO as in dev.
