### ISSUE TITLE
Look into VIVO views to cross-link instruments with datasets (already done the other way around)

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#13]

**Comment by cbsnyder** [comment]
The instruments show up on each dataset's page as "source instrument." On each instrument's page there is a property called "has input dataset." It looks like we would like the the datasets each instrument is associated with to show up here. 
I'm not totally sure yet how to do this. I read that it is possible to make a property an "inverse property." An inverse property shows object properties as pairs in both directions - from the subject to the object and vice-versa. Perhaps making "source instrument" an inverse property will accomplish this? 

In the Object Property Control Panel I can find the Property Editing Form for source instrument. "Inverse property ontology" is set to "default" but you can not edit the fields, it says "Edit via 'change URI' on previous screen." The URI is http://data.globalchange.gov/gcis.owl#sourceInstrument. I'm not sure how to change this to make it an inverse property, or if that will accomplish the desired result.

**Comment by cbsnyder** [comment]
Matt and John's schema update on vivo.dev has been successful in creating the inverse relationship between dataset and instrument. Datasets are listed under "Source Instrument For" on each corresponding instrument's page. On each dataset's page associated instruments are listed under "source instrument."

**Comment by cbsnyder** [comment]
The same inverse property can next be set up for platforms (on the development site first).

**Comment by jja** [comment]
`sourceInstrumentFor` and `sourcePlatformFor` have been merged #14 and deployed to production
