### ISSUE TITLE
Earthcollab schema has no title

### ISSUE THREAD

**Issue by gneissone** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#16]
^^^^^^^
Add a title to the schema so it looks nice in VIVO

<https://library.ucar.edu/earthcollab/schema>
        a                          owl:Ontology ;
        rdfs:label                 "EarthCollab Schema"@en-US ;
        vitro:ontologyPrefixAnnot  "ec"^^xsd:string .

**Comment by mayernik** [comment]
I made this addition to the EarthCollab ontology. I also added a new property - ec:sourceInstrumentFor, which is defined as an inverse property of gcis:sourceInstrument
