### ISSUE TITLE
Create a todo list for Erica's usability testing

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#22]
During the August 7, 2017 telecon, Erica mentioned that she would like to do some usability testing on our VIVO instance. On the call, we targeted October as a good time to do this.

**Comment by daniels303** [comment]
Our initial plan will be to interview approximately 10 outside users to get their feedback on our VIVO instance and its usability. We would also like to separate publications from datasets when viewing a researcher's products.

**Comment by daniels303** [comment]
This was discussed at the EarthCollab All-Hands [telecon of Nov 3, 2017](https://docs.google.com/document/d/1WVH3Cod90vU3YG6XgqV0OWkpJ5AXfy0GlTC9UhgZ6-A/edit). As a next step, Erica will send the outcomes of the UNAVCO usability testing.

**Comment by daniels303** [comment]
Here are [Erica and Huda's notes](https://docs.google.com/document/d/1WZXaSx9OMyTFIor-LNxgs-oqsNKXNp49CIVl_EGGrbw/edit) from prior usability testing.

**Comment by dwstott** [comment]
Usability questions determined in meeting with Matt, Don, and Mike.
