### ISSUE TITLE
Separate publications from datasets in "Other" profile for an Investigator

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#24]
As per the EarthCollab telecon on Nov 3, 2017, the list of publications and datasets for an author needs to be sorted so that they are easier to parse. See [Lee Cooper's page under the "Other" tab and the heading "is author of"](http://vivo.eol.ucar.edu/vivo/individual?uri=https%3A%2F%2Fdata.eol.ucar.edu%2Fcontact%2F52).

**Comment by cbsnyder** [comment]
I completed this task by replacing the content of the "is author of" section (on the Other tab) with a template that uses a DataGetter to retrieve the contents which are grouped by type (Dataset, Publication, etc.) in their own sections with sub-headers. 
The feature has been pushed to the master branch and deployed on production VIVO.
Some examples:
http://vivo.eol.ucar.edu/vivo/individual?uri=https%3A%2F%2Fdata.eol.ucar.edu%2Fcontact%2F52
http://vivo.eol.ucar.edu/vivo/individual?uri=https%3A%2F%2Fdata.eol.ucar.edu%2Fcontact%2F1204
http://vivo.eol.ucar.edu/vivo/individual?uri=https%3A%2F%2Fdata.eol.ucar.edu%2Fcontact%2F421

**Comment by cbsnyder** [comment]
I have now integrated this feature into the new version (1.9) of VIVO which has been merged into the develop branch and deployed on vivo.dev.

**Comment by dwstott** [comment]
works
