### ISSUE TITLE
Prepare and summarize outcomes of the Open Science Meeting

### ISSUE THREAD

**Issue by dwstott** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#26]
Arrange to meet with PIs for usability testing and assist with linking publications to datasets at OSM in February.

**Comment by dwstott** [comment]
Prepared 86 Word docs for each investigator listed as an author.  The doc has their datasets and  publications in lists and asking them to drag the publications beneath the related dataset. Will send out when all profile images are in the VIVO.

**Comment by daniels303** [comment]
On February 16, Don and I talked about listing the most desired features/changes from the PIs that came out of this meeting. This summary would help inform the remaining tasks for EOL's VIVO instance.

**Comment by dwstott** [comment]
Summaries on drive at
https://drive.google.com/drive/folders/1H1l8-wEUF0vKnIDUI9vEUSMx-0lWLIJS?usp=sharing
