### ISSUE TITLE
Connect datasets to cruises

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#27]
Select by cruise: We currently have 267 Bering Sea Project datasets identified by ship and cruise. We have cruises entered in the Mapserver for the Bering Sea Project at http://mapserver.eol.ucar.edu/bestcruises/ Carin Ashjian suggested a simple cruise track map linked to a list of cruises would help people identify the cruises. These tracks can be illustrated by screen shots, per cruise, from the mapserver, as illustrated below.

Connecting datasets to cruises may be challenging since we don’t have cruises in our ontologies, but I expect that the geolink ontology ( http://schema.geolink.org ) will facilitate linking the two. If we find it will meet our needs, then entering the code for the linking is a detail oriented scripting task. Preparing the images of the cruise tracks and getting them into VIVO in a usable fashion may take more time than one might first think.

**Comment by dwstott** [comment]
Adam S. at WHOI for geo ontology questions, ashepherd@whoi.edu

**Comment by heesuchang** [comment]
I've been experimenting with the geolink ontology real quick in vivo.dev and it seems to look good.
[http://vivo.dev.eol.ucar.edu/vivo/display/n2150](http://vivo.dev.eol.ucar.edu/vivo/display/n2150) 

You can see on the cruise page that they do have a hasTrack property but only supports text and links. I don't think we'll be able to post an image here directly, but I did find this page that has a link to a pdf of the cruise track. Unfortunately, the link on this page is dead. [http://icefloe.net/forms/submitted/?recordID=678](http://icefloe.net/forms/submitted/?recordID=678) 

Perhaps we might want to find or host links to the various screenshots and use that for the "hasTrack"?

**Comment by heesuchang** [comment]
It turns out we can upload the screenshot into the profile picture of each cruise. Though the thumbnail will be cropped, we can link the full size screenshot in the "hasTrack" property. 

[example](http://vivo.dev.eol.ucar.edu/vivo/individual?uri=http%3A%2F%2Fvivo.eol.ucar.edu%2Fvivo%2Fcruise%2Fn2&extra=true)

HLY-06-02 and HLY-07-02 aren't on the mapserver. I will use the tracks from the following resource until better tracks can be found.

[Healy Cruise Catalog](http://www.rvdata.us/catalog/Healy)

**Comment by heesuchang** [comment]
Geolink Base Ontology has been deployed in production and the tracks have all been ingested.
[Prod Example](http://vivo.eol.ucar.edu/vivo/individual?uri=http%3A%2F%2Fvivo.eol.ucar.edu%2Fvivo%2Fcruise%2Fn8)
