### ISSUE TITLE
EOL: Acquire ORCiDs for Bering Sea Researchers

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#3]

**Comment by daniels303** [comment]
Have a list in Michaeleen's spreadsheet, ORCiDs are now required to submit data to the Arctic Data Center. Should be able to either take them off of the spreadsheet or find them via search.

**Comment by daniels303** [comment]
Mike can search for existing ORCiDs and update the spreadsheet.

**Comment by daniels303** [comment]
Spent about 1.5 hours searching for ORCiDs for about 30 researchers.

__I did not find ORCiDs for:__
Aydin | Kerim
Bailey | Kevin
Cokelet | Ned
Dalton | Michael
DeRobertis | Alex
Fall | Jim
Farley | Ed
Friday | Nancy
Hollowed | Anne
Irons | David
Jay | Chad
Kitaysky | Sasha
Kruse | Sarah
Kruse | Gordon
Laurel | Ben
Lauth | Bob
Napp | Jeff
Noongwook | George
Renner | Heather
Sepez | Jennifer
Moran | Brad
Bond | Nicholas

__I found and verified ORCiDs for these researchers:__
Clapham | Phil: http://orcid.org/0000-0002-2776-5746
Ianelli | James: http://orcid.org/0000-0002-7170-8677
Kuletz | Kathy: http://orcid.org/0000-0001-5685-3422
Barbeaux | Steven: http://orcid.org/0000-0001-9498-0369

__and I found but could not verify ORCiDs for these researchers:__
Trites | Andrew: http://orcid.org/0000-0003-0342-5322
Zerbini | Alex: http://orcid.org/0000-0002-9776-6605
Heppell | Scott: http://orcid.org/0000-0003-1387-8181

__The following researchers had common names which made it difficult to find a valid ORCiD for them, if they had one:__
Wilson | Chris
Campbell | Robert

Based on the time spent for these ~ 30 researchers, I consider this issue a fairly time-intensive, "last mile" sort of project. We should discuss the feasibility and cost of doing a manual search in this way. There are about 74 researchers left to search for.

**Comment by daniels303** [comment]
Hee has some ORCiDs that may not be in the spreadsheet I have. He will forward this list to me so that I can remove them from the search. [Here is the spreadsheet](https://docs.google.com/spreadsheets/d/1fLeLnREhmvz63T9BG6AAx7zO6D5Qs5X2Nqp_WGFkT40/edit#gid=794056073) I'm working from.

**Comment by daniels303** [comment]
Hee sent me the spreadsheet and I verified that there was only one ORCiD that was not accounted for - Lee Cooper.

**Comment by daniels303** [comment]
Finished the search.

__ORCiDs were found and verified for:__
Hedström	Kate https://orcid.org/0000-0001-5411-2313
Sambrotto	Raymond https://orcid.org/0000-0003-1305-2224
Wu	Jingfeng https://orcid.org/0000-0003-0156-1507
Aguilar-Islas	Ana https://orcid.org/0000-0003-1987-7841
Rynearson	Tatiana https://orcid.org/0000-0003-2951-0066
Smith	Sharon https://orcid.org/0000-0003-0457-2949

__ORCiDs were found but NOT verified for:__
Frey	Karen https://orcid.org/0000-0002-8745-1298
Fu	Hongli https://orcid.org/0000-0002-6962-2671
Holsman	Kirstin https://orcid.org/0000-0001-6361-2256
Jimmy	Michael https://orcid.org/0000-0001-9554-2512
Lovvorn	James https://orcid.org/0000-0002-0720-5047
Rember	Robert https://orcid.org/0000-0001-7747-5934

__The following researchers had names that were common and led to multiple ORCiDs:__
Brown	Caroline

__The following researchers did not have contact information which meant finding ORCiDs for them was not possible:__
Casas	Maria

All others in the spreadsheet did not have ORCiDs.

The full color-coded spreadsheet is [here](https://docs.google.com/spreadsheets/d/1fLeLnREhmvz63T9BG6AAx7zO6D5Qs5X2Nqp_WGFkT40/edit#gid=794056073).

**Comment by daniels303** [comment]
Next the EMDAC and VIVO databases need to be updated with these newly found ORCiDs. This task will be assigned to Hee.

**Comment by heesuchang** [comment]
EMDAC and VIVO databases have been updated with the new ORCiDs and have been "confirmed" for each profile in VIVO.
