### ISSUE TITLE
EOL: Install latest version of VIVO, fix any errors that pop up

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#5]

**Comment by daniels303** [comment]
Should be worked on by Ted and John.

**Comment by jja** [comment]
Not Ted but Don could work on this if he wanted/has time...

**Comment by jja** [comment]
To clarify: the point of my last comment is that Ted should not be tasked with the upgrade, but if Don is available then he is an alternative to me.

The point of the reference from #12 is that upgrading should resolve #12 .

**Comment by dwstott** [comment]
Will look into what will be involved/affected next week.

**Comment by dwstott** [comment]
Should be able to upgrade to v1.9.1 with configuration and Maven changes, without doing a complete reinstall. https://wiki.duraspace.org/display/VIVODOC19x/Upgrading+VIVO
Am checking this out on wombat-dev.

**Comment by dwstott** [comment]
1.9.2 vivo running on vivo-dev.eol.ucar.edu for testing

**Comment by heesuchang** [comment]
We will be upgrading to version 1.9.3, which is the last 1.9.X version.

**Comment by dwstott** [comment]
Configuration changes made. In process of updating java and maven on vivo-dev, then will try the first build on testing vm.

**Comment by dwstott** [comment]
Configurations made to build v1.9.3 with new maven structure and our own Vivo customizations. Have a war file; will test with Tomcat.

**Comment by heesuchang** [comment]
Version 1.9.3 upgrade of existing code tested and running on http://vivo-dev.eol.ucar.edu/vivo_full
Configurations for stage-specific build have been made. Progress tracked on "feature/rel-1.9.3" branch

**Comment by jja** [comment]
Since this was merged to develop but then broke our deploy of #24, I've fixed it on develop and it's running on http://vivo.dev.eol.ucar.edu/vivo/

**Comment by cbsnyder** [comment]
The separating datasets and publications feature [#24](https://github.com/NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930/issues/24) has been integrated into the new version of VIVO and merged into the develop branch. This is now running on the dev instance [http://vivo.dev.eol.ucar.edu/vivo/](http://vivo.dev.eol.ucar.edu/vivo/)

**Comment by cbsnyder** [comment]
Worked with John to fix a small VIVO submodule reference problem that I created by mistake. The cleaned up version of develop has been deployed to vivo.dev.

**Comment by dwstott** [comment]
updated vivo.dev to 1.9.3

**Comment by dwstott** [comment]
updated prod vivo to v1.9.3
