### ISSUE TITLE
EOL: Load all the platforms and instruments from the EMDAC database into VIVO for the Bering Sea Project datasets we have already loaded 

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#7]

**Comment by daniels303** [comment]
Brooks is working on this right now. On the development site and working on putting it into production.

**Comment by cbsnyder** [comment]
The instruments and platforms have been loaded to vivo-dev. The instruments have also been loaded to production vivo, but an ontology update is needed before we can do platforms on production.

**Comment by cbsnyder** [comment]
Note - removing/re-loading the ontology in VIVO is only temporary the src needs to be updated for permanent change.

**Comment by jja** [comment]
EC ontology updated by #14 re: #13 and @cbsnyder loaded the platforms to production
