### ISSUE TITLE
EOL: Fix problem with qualified attributions for researchers (EMDAC extended contact metadata), e.g. references between different fields are not working

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#8]

**Comment by daniels303** [comment]
Brooks thinks this could be related to blank lines in the qualified attributes field of the VIVO database.

**Comment by cbsnyder** [comment]
In the RDS model the blank qualified attributions always show up like this (or something similar): 
` <http://www.w3.org/ns/prov#qualifiedAttribution>
                <https://data.eol.ucar.edu/dataArchive/1> , <https://data.eol.ucar.edu/author/1209> , <https://data.eol.ucar.edu/author/707> , <https://data.eol.ucar.edu/publisher/1001> , <https://data.eol.ucar.edu/pointOfContact/1> ;
        <http://www.w3.org/ns/prov#qualifiedAttribution>
                []  ;
        <http://www.w3.org/ns/prov#qualifiedAttribution>
                []  ;
        <http://www.w3.org/ns/prov#qualifiedAttribution>
                []  ;
        <http://www.w3.org/ns/prov#qualifiedAttribution>
                []  ;
        <http://www.w3.org/ns/prov#qualifiedAttribution>
                []  ;
        <http://www.w3.org/ns/prov#qualifiedAttribution>
                []  .
`

**Comment by jja** [comment]
I think I finally figured it out: VIVO does not like blank nodes, and must associate a `rdfs:label`. The trick now will be to delete the old/bad nodes.

**Comment by jja** [comment]
Examples loaded on our dev site, e.g. [245.B69-003](http://vivo.dev.eol.ucar.edu/vivo/individual?uri=https%3A%2F%2Fdata.eol.ucar.edu%2Fdataset%2F245.B69-003#qualifiedAttribution)

**Comment by jja** [comment]
Fixed/finalized on dev site e.g. [245.B57-001](http://vivo.dev.eol.ucar.edu/vivo/individual?uri=https%3A%2F%2Fdata.eol.ucar.edu%2Fdataset%2F245.B57-001#qualifiedAttribution)

@cbsnyder Brooks, perhaps you can look at the contact templates? ...and see if we can get all the qualifiedAttributions to be listed there e.g. on [Jackie's page](http://vivo.dev.eol.ucar.edu/vivo/individual?uri=https%3A%2F%2Fdata.eol.ucar.edu%2Fcontact%2F421)

**Comment by cbsnyder** [comment]
I'll have a look.

**Comment by cbsnyder** [comment]
Trying to display qualifiedAttributions on each contact's page using a DataGetter as described [here](https://wiki.duraspace.org/display/VTDA/Enriching+profile+pages+using+SPARQL+query+DataGetters). The SPARQL query seems to provide what is needed based on experimentation with the tool in the Site Admin. The DataGetter and associated template has been created, but it still needs to be determined as to how to incorporate this into the existing templates and then tested.

**Comment by cbsnyder** [comment]
On vivo.dev an contact's page will now list that contacts qualifiedAttributions (and what type of attribution, ie. originator, author, principalInvestigator), however the same dataset could potentially be listed three times this way. 
Currently, working on the freemarker code to organize the output. I may need to see how/if I can generalize my freemarker template so that it is more general (so new types of qualifiedAttributions don't need to be added to the code if they appear).

**Comment by cbsnyder** [comment]
The DataGetter and custom template to display the qualifiedAttributions on each person's page is now working and has been deployed to both vivo.dev and the production site.
