### ISSUE TITLE
EOL: Match publications to ontologies (can be difficult due to versions, term mismatches, etc.), determining which fields go into which parts of the schema

### ISSUE THREAD

**Issue by daniels303** [NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930#9]

**Comment by daniels303** [comment]
Has to be done after we meet with Benjamin.

**Comment by cbsnyder** [comment]
Here is a link to the relationship diagram that Benjamin presented (and also more generally a link to the VIVO wiki.duraspace.org page that contains a lot of useful info):
https://wiki.duraspace.org/display/VTDA/VIVO-ISF+1.6+relationship+diagrams%3A+Authorship

**Comment by dwstott** [comment]
Ontologies utilized when publications/authors added from spreadsheet.
